[package]
name = "variant-set"
version = "0.1.0"
edition = "2021"
description = "A set-like data structure for enum variants, allowing you to store at most one value for each variant of an enum."

[dependencies]
nohash-hasher = "0.2.0"
variant-set-derive = { path = "../variant-set-derive" }
