[package]
name = "variant-set-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for the variant-set crate"
license = "CC0-1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = "2.0.79"
